"""add owner id column to posts table

Revision ID: 9d24f534f56c
Revises: 8761922f5b36
Create Date: 2025-03-07 18:36:08.922179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.database.models import User, Post


# revision identifiers, used by Alembic.
revision: str = '9d24f534f56c'
down_revision: Union[str, None] = '8761922f5b36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.execute('UPDATE posts SET owner_id = 1 WHERE owner_id IS NULL;')
    op.alter_column('posts', 'owner_id', nullable=False)
    op.create_foreign_key(None, 'posts', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'owner_id')
    # ### end Alembic commands ###
